export const ATTRIBUTES = {
  absorb: "Absorption",
  scent: "Scent",
  texture: "Texture",
  irritate: "Irritation",
  matte: "Matte",
  dewy: "Dewy",
  glow: "Glow",
  bright: "Brightening",
  plump: "Plumping",
  smooth: "Smoothening",
  firm: "Firming",
  greasy: "Greasy",
  hydrate: "Hydrating",
  red: "Redness",
  redness: "Redness",
  shine: "Shine",
  pigment: "Pigmentation",
  aging: "Aging",
  acne: "Acne, Blemishes",
  pores: "Pores",
  lightweight: "Lightweight",
  "oily skin": "Oily Skin",
  "sensitive skin": "Sensitive Skin",
  "dry skin": "Dry Skin",
  "normal skin": "Normal Skin",
  "combination skin": "Combination Skin"
};
