export const ATTRIBUTES = {
  absorb: "Absorption",
  scent: "Scent",
  texture: "Texture",
  irritate: "Irritation",
  matte: "Matte",
  glow: "Glow/ Brightening/ Dewy",
  smooth: "Softer/ Smoother Skin",
  firm: "Firming",
  greasy: "Greasy",
  hydrate: "Hydrating",
  red: "Redness",
  redness: "Redness",
  oiliness: "Oiliness",
  pigment: "Pigmentation",
  aging: "Aging",
  acne: "Acne, Blemishes",
  pores: "Pores",
  rosacea: "rosacea",
  eczema: "eczema",
  lightweight: "Lightweight",
  "oily skin": "Oily Skin",
  "sensitive skin": "Sensitive Skin",
  "dry skin": "Dry Skin",
  "normal skin": "Normal Skin",
  "combination skin": "Combination Skin"
};
